# Generated by Django 5.0 on 2023-12-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Reaction',
            name = 'reaction_type',
            field=models.CharField(max_length=10, choices=[('upvote', 'UpVote'), ('downvote', 'DownVote')])
        )

    ]
