# Generated by Django 5.0 on 2023-12-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231212_0537'),
    ]

    operations = [
    ]
